### ISSUE TITLE
Allow at least one error before removing cogs from Index

### ISSUE THREAD

**Issue by jack1142** [Cog-Creators/Red-Index#11]
I think it would be good if Index could leverage the current version of its JSON data when the repository link becomes temporarily unavailable so that it doesn't become immediately remove from the Index. I suggest that Index keeps some state of the repositories in a file and if it fails to fetch, it should update that state so that it removes the link *next time* it tries to fetch and fails. And if it doesn't fail next time, it would get treated as a temporary failure and the state would be cleared.

**Comment by Twentysix26** [comment]
I'm a bit on the #wontfix side here.
The purpose of this service is to provide an *up-to-date* list of repos that are available when it's run, whether that's manual or scheduled.
Allowing *one* failure seems a bit arbitrary and introduces additional complexity for not a lot of benefits (I'm assuming you're proposing this due to the recent GitLab's small downtimes and the new-cogs tool posting removals + additions).
The service here is technically not doing anything wrong: the repos are *not* available at runtime and attempting to clone them would result in an error. I see this as a problem that would better be handled on the client side rather than the source side.

**Comment by jack1142** [comment]
> I see this as a problem that would better be handled on the client side rather than the source side.

The problem with that is that *every* service (client) would have to handle it on its own, be that Index cog, Cog-Browser site, the new-cogs tool posting removal/additions, or anything else. This adds to the complexity of *each* of these clients where it could (theoretically) all be improved on the source-side.

> I'm a bit on the #wontfix side here.
> The purpose of this service is to provide an up-to-date list of repos that are available when it's run, whether that's manual or scheduled.

To be fair though, it's not that I'm all that surprised with this opinion as I was wondering whether I should make this issue too. The solution I provided does seem a bit iffy, but downtimes happen and it isn't really all that good that users might simply not find a cog they were looking for just because they happened to search for it when the repository had downtime. That's not how search engines work.

> Allowing *one* failure seems a bit arbitrary and introduces additional complexity for not a lot of benefits (I'm assuming you're proposing this due to the recent GitLab's small downtimes and the new-cogs tool posting removals + additions).

Here's another idea, which depends on how long these downtimes really are (cause I don't really know). Maybe a simple exponential retry would suffice? It would mean that the job could take a bit longer to run sometimes, but the complexity of such a solution should (probably) be smaller than what I proposed in the issue description.

**Comment by Twentysix26** [comment]
> That's not how search engines work.
I can see your point.  
> Maybe a simple exponential retry would suffice? It would mean that the job could take a bit longer to run sometimes, but the complexity of such a solution should (probably) be smaller than what I proposed in the issue description.

This might be good enough, however at the moment the repo cloning is decoupled from the parser (it's a bash script), so that's not a super quick fix either
