### ISSUE TITLE
Adding my repo StarCogs

### ISSUE THREAD

**Issue by NightStar-s** [Cog-Creators/Red-Index#118]
I do like to get my repo added in Redbot Community

My repo link: https://github.com/NightStar-s/StarCogs

**Comment by Flame442** [comment]
Your repo is currently in breech of the license for the cog you have forked (`Leveler`), as it is not redistributing the license under which it was released (GNU General Public License v3.0). You need to address this before your repo can be added to the unapproved list.

When you have resolved this issue, please create a **pull request** adding your repository to the unapproved section of `repositories.txt`, similar to previous PRs (https://github.com/Cog-Creators/Red-Index/pull/116).

Additionally, there are a few other non-blocking issues I noticed that you should consider fixing:
- `bmico`'s `info.json` has a field called `authors`. This field must be called `author`, despite being a list (for legacy reasons).
- `bmico.py` has a `setup` function that is going to be unused. The setup function in `__init__.py` is the correct one that will be used by the bot to initialize the cog.
- Your repo is missing a license for the code you have written. In most jurisdictions, code shared without a license that at least allows usage technically cannot legally be used.
