### ISSUE TITLE
curl \   -X POST \   -H "Accept: application/vnd.github.v3+json" \   https://api.github.com/repos/octocat/hello-world/keys \   -d '{"key":"key"}'

### ISSUE THREAD

**Issue by nahnicholas** [Cog-Creators/Red-Index#13]

**Comment by nahnicholas** [comment]
Whats the issue

**Comment by jack1142** [comment]
Hello there, could you explain what you're trying to do? Your issue title and description sadly do not explain much.

**Comment by jack1142** [comment]
I'm closing this issue as invalid because it does not have any information. Feel free to make a new issue with an explanation of what is happening and how it happened if you do actually have an issue to report.
