### ISSUE TITLE
Blizz-cogs spam

### ISSUE THREAD

**Issue by Fabian-Evolved** [Cog-Creators/Red-Index#132]
Anybody know why this blizz cog spam keeps happening in the index updates?

it's crazy how many commits are about the removal of the repository and the addition of it in the last couple weeks/months.

**Comment by Flame442** [comment]
They are using a self hosted git instance that is 530ing about every 12 hours. They think it is due to ISP dropouts, and are having someone look into it soon. [[ref](https://discord.com/channels/133049272517001216/133081046869737472/1242879547100106842)]

**Comment by Flame442** [comment]
This issue appears to be resolved now.
